---

- name: Add the RabbitMQ public GPG key to the apt repo
  apt_key: url=https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
           state=present

- name: Add RabbitMQ to the sources list
  apt_repository: 
    repo: 'deb https://dl.bintray.com/rabbitmq/debian testing main'
    update_cache: yes
    state: present

- name: Install RabbitMQ server
  apt: 
    name: rabbitmq-server
    update_cache: yes
    force: yes 
    state: installed

- name: Clean apt cache
  command: apt-get clean
  when: ansible_os_family == 'Debian'
